[package]
name = "ex_fastembed"
version = "0.1.0"
authors = []
edition = "2021"
rust-version = "1.91"

[lib]
name = "ex_fastembed"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
fastembed = { version = "5", default-features = false, features = ["hf-hub-native-tls", "ort-download-binaries-native-tls"] }
rustler = "0.38.0"

[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"
