[package]
name = "ex_fastembed"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ex_fastembed"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
fastembed = "4.6.0"
rustler = "0.36.1"

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'
strip = "debuginfo"
